In [20]:
import os
from collections import Counter

IMAGE_DIR = "../detection_dataset/images/train"
LABEL_DIR = "../detection_dataset/labels/train"

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

missing_labels = []
missing_images = []
empty_labels = []
invalid_labels = []

class_counter = Counter()

total_images = 0
total_annotations = 0

In [21]:
image_files = [
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith(IMAGE_EXTENSIONS)
]

label_files = [
    f for f in os.listdir(LABEL_DIR)
    if f.endswith(".txt")
]

print(f"Total Image Files: {len(image_files)}")
print(f"Total Label Files: {len(label_files)}")

Total Image Files: 622
Total Label Files: 617

In [22]:
for image_file in image_files:

    total_images += 1

    image_name = os.path.splitext(image_file)[0]
    label_file = image_name + ".txt"

    label_path = os.path.join(LABEL_DIR, label_file)

    if not os.path.exists(label_path):
        missing_labels.append(image_file)
        continue

    if os.path.getsize(label_path) == 0:
        empty_labels.append(label_file)
        continue

    with open(label_path, "r") as f:
        lines = f.readlines()

    for line in lines:

        parts = line.strip().split()

        if len(parts) != 5:
            invalid_labels.append(label_file)
            continue

        class_id = parts[0]

        class_counter[class_id] += 1
        total_annotations += 1

In [19]:
print("\n========== DATASET REPORT ==========")

print(f"\nTotal Images: {total_images}")
print(f"Total Annotations: {total_annotations}")

print("\nClass Distribution:")
print(f"Healthy (0): {class_counter['0']}")
print(f"Unhealthy (1): {class_counter['1']}")

print("\nMissing Labels:", len(missing_labels))
print("Empty Labels:", len(empty_labels))
print("Invalid Labels:", len(invalid_labels))
print("Missing Images:", len(missing_images))

========== DATASET REPORT ==========

Total Images: 622
Total Annotations: 1217

Class Distribution:
Healthy (0): 668
Unhealthy (1): 549

Missing Labels: 6
Empty Labels: 0
Invalid Labels: 0
Missing Images: 0

In [23]:
print("========== MISSING LABEL FILES ==========\n")

for item in missing_labels:
    print(item)

========== MISSING LABEL FILES ==========

healthy_0018.jpg
healthy_0038.jpg
healthy_0057.jpg
healthy_0059.jpg
healthy_0343.jpg
healthy_0157.jpg

Resized image image number

In [31]:
import os

healthy_path = "../resized_images/healthy01"
unhealthy_path = "../resized_images/unhealthy01"

healthy_count = len([
    f for f in os.listdir(healthy_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

unhealthy_count = len([
    f for f in os.listdir(unhealthy_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

total_images = healthy_count + unhealthy_count

print("========== RESIZED IMAGE REPORT ==========\n")

print(f"Healthy Images   : {healthy_count}")
print(f"Unhealthy Images : {unhealthy_count}")
print(f"Total Images     : {total_images}")

========== RESIZED IMAGE REPORT ==========

Healthy Images   : 305
Unhealthy Images : 90
Total Images     : 395

In [1]:
# Detection dataset images number

In [32]:
import os

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

# Paths
train_path = "../detection_dataset/images/train"
val_path = "../detection_dataset/images/val"
test_path = "../detection_dataset/images/test"

# Count function
def count_images(folder):

    return len([
        f for f in os.listdir(folder)
        if f.lower().endswith(IMAGE_EXTENSIONS)
    ])

# Counts
train_count = count_images(train_path)
val_count = count_images(val_path)
test_count = count_images(test_path)

total_count = train_count + val_count + test_count

# Report
print("========== DETECTION DATASET REPORT ==========\n")

print(f"Train Images : {train_count}")
print(f"Val Images   : {val_count}")
print(f"Test Images  : {test_count}")

print("\n-----------------------------")

print(f"Total Images : {total_count}")

========== DETECTION DATASET REPORT ==========

Train Images : 622
Val Images   : 179
Test Images  : 92

-----------------------------
Total Images : 893

In [34]:
import os
from collections import Counter

# =====================================
# DATASET PATHS
# =====================================

IMAGE_DIRS = [
    "../detection_dataset/images/train",
    "../detection_dataset/images/val",
    "../detection_dataset/images/test"
]

LABEL_DIRS = [
    "../detection_dataset/labels/train",
    "../detection_dataset/labels/val",
    "../detection_dataset/labels/test"
]

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

# =====================================
# COUNTERS
# =====================================

missing_labels = []
missing_images = []
empty_labels = []
invalid_labels = []

class_counter = Counter()

total_images = 0
total_annotations = 0

# =====================================
# CHECK ALL SPLITS
# =====================================

for IMAGE_DIR, LABEL_DIR in zip(IMAGE_DIRS, LABEL_DIRS):

    image_files = [
        f for f in os.listdir(IMAGE_DIR)
        if f.lower().endswith(IMAGE_EXTENSIONS)
    ]

    label_files = [
        f for f in os.listdir(LABEL_DIR)
        if f.endswith(".txt")
    ]

    # -----------------------------
    # IMAGE -> LABEL
    # -----------------------------

    for image_file in image_files:

        total_images += 1

        image_name = os.path.splitext(image_file)[0]
        label_file = image_name + ".txt"

        label_path = os.path.join(LABEL_DIR, label_file)

        # Missing label
        if not os.path.exists(label_path):
            missing_labels.append(image_file)
            continue

        # Empty label
        if os.path.getsize(label_path) == 0:
            empty_labels.append(label_file)
            continue

        # Read labels
        with open(label_path, "r") as f:
            lines = f.readlines()

        for line in lines:

            parts = line.strip().split()

            # YOLO format check
            if len(parts) != 5:
                invalid_labels.append(label_file)
                continue

            class_id = parts[0]

            class_counter[class_id] += 1
            total_annotations += 1

    # -----------------------------
    # LABEL -> IMAGE
    # -----------------------------

    for label_file in label_files:

        label_name = os.path.splitext(label_file)[0]

        image_found = False

        for ext in IMAGE_EXTENSIONS:

            image_path = os.path.join(
                IMAGE_DIR,
                label_name + ext
            )

            if os.path.exists(image_path):
                image_found = True
                break

        if not image_found:
            missing_images.append(label_file)

# =====================================
# FINAL REPORT
# =====================================

print("\n========== FULL DATASET REPORT ==========")

print(f"\nTotal Images: {total_images}")
print(f"Total Annotations: {total_annotations}")

print("\nClass Distribution:")
print(f"Healthy (0): {class_counter['0']}")
print(f"Unhealthy (1): {class_counter['1']}")

print("\nMissing Labels:", len(missing_labels))
print("Empty Labels:", len(empty_labels))
print("Invalid Labels:", len(invalid_labels))
print("Missing Images:", len(missing_images))

# =====================================
# OPTIONAL DETAILS
# =====================================

if missing_labels:

    print("\n========== MISSING LABEL FILES ==========\n")

    for item in missing_labels:
        print(item)

========== FULL DATASET REPORT ==========

Total Images: 893
Total Annotations: 1748

Class Distribution:
Healthy (0): 897
Unhealthy (1): 851

Missing Labels: 7
Empty Labels: 1
Invalid Labels: 0
Missing Images: 3

========== MISSING LABEL FILES ==========

healthy_0018.jpg
healthy_0038.jpg
healthy_0057.jpg
healthy_0059.jpg
healthy_0343.jpg
healthy_0157.jpg
healthy_0108.jpg

In [36]:
import os
from collections import Counter, defaultdict

# =====================================
# DATASET PATHS
# =====================================

SPLITS = ["train", "val", "test"]

BASE_IMAGE_DIR = "../detection_dataset/images"
BASE_LABEL_DIR = "../detection_dataset/labels"

IMAGE_EXTENSIONS = (".jpg", ".jpeg", ".png")

# =====================================
# GLOBAL COUNTERS
# =====================================

missing_labels = defaultdict(list)
missing_images = defaultdict(list)
empty_labels = defaultdict(list)
invalid_labels = defaultdict(list)

class_counter = Counter()

split_image_count = Counter()
split_annotation_count = Counter()

total_images = 0
total_annotations = 0

# =====================================
# CHECK ALL SPLITS
# =====================================

for split in SPLITS:

    IMAGE_DIR = os.path.join(BASE_IMAGE_DIR, split)
    LABEL_DIR = os.path.join(BASE_LABEL_DIR, split)

    print(f"\n========== CHECKING {split.upper()} ==========")

    image_files = [
        f for f in os.listdir(IMAGE_DIR)
        if f.lower().endswith(IMAGE_EXTENSIONS)
    ]

    label_files = [
        f for f in os.listdir(LABEL_DIR)
        if f.endswith(".txt")
    ]

    split_image_count[split] = len(image_files)

    # ---------------------------------
    # IMAGE -> LABEL CHECK
    # ---------------------------------

    for image_file in image_files:

        total_images += 1

        image_name = os.path.splitext(image_file)[0]
        label_file = image_name + ".txt"

        label_path = os.path.join(LABEL_DIR, label_file)

        # Missing label
        if not os.path.exists(label_path):

            missing_labels[split].append(image_file)
            continue

        # Empty label
        if os.path.getsize(label_path) == 0:

            empty_labels[split].append(label_file)
            continue

        # Read label file
        with open(label_path, "r") as f:
            lines = f.readlines()

        split_annotation_count[split] += len(lines)
        total_annotations += len(lines)

        for line in lines:

            parts = line.strip().split()

            # Invalid YOLO format
            if len(parts) != 5:

                invalid_labels[split].append(label_file)
                continue

            class_id = parts[0]

            class_counter[class_id] += 1

    # ---------------------------------
    # LABEL -> IMAGE CHECK
    # ---------------------------------

    for label_file in label_files:

        label_name = os.path.splitext(label_file)[0]

        image_found = False

        for ext in IMAGE_EXTENSIONS:

            image_path = os.path.join(
                IMAGE_DIR,
                label_name + ext
            )

            if os.path.exists(image_path):

                image_found = True
                break

        if not image_found:

            missing_images[split].append(label_file)

# =====================================
# FINAL REPORT
# =====================================

print("\n\n========== FULL DATASET REPORT ==========")

print(f"\nTotal Images: {total_images}")
print(f"Total Annotations: {total_annotations}")

# -------------------------------------
# SPLIT DISTRIBUTION
# -------------------------------------

print("\n========== SPLIT DISTRIBUTION ==========")

for split in SPLITS:

    print(f"\n{split.upper()}")

    print(f"Images       : {split_image_count[split]}")
    print(f"Annotations  : {split_annotation_count[split]}")

# -------------------------------------
# CLASS DISTRIBUTION
# -------------------------------------

print("\n========== CLASS DISTRIBUTION ==========")

print(f"Healthy (0)   : {class_counter['0']}")
print(f"Unhealthy (1) : {class_counter['1']}")

# -------------------------------------
# LABELING STATUS
# -------------------------------------

print("\n========== LABELING STATUS ==========")

for split in SPLITS:

    total_missing = len(missing_labels[split])

    print(f"\n{split.upper()}")

    print(f"Need Labeling : {total_missing}")

    if total_missing > 0:

        print("\nMissing Label Files:")

        for item in missing_labels[split]:
            print(f"  - {item}")

# -------------------------------------
# OTHER ISSUES
# -------------------------------------

print("\n========== OTHER ISSUES ==========")

for split in SPLITS:

    print(f"\n{split.upper()}")

    print(f"Missing Images : {len(missing_images[split])}")
    print(f"Empty Labels   : {len(empty_labels[split])}")
    print(f"Invalid Labels : {len(invalid_labels[split])}")

# -------------------------------------
# EMPTY LABEL DETAILS
# -------------------------------------

for split in SPLITS:

    if empty_labels[split]:

        print(f"\n========== {split.upper()} EMPTY LABELS ==========\n")

        for item in empty_labels[split]:
            print(item)

# -------------------------------------
# INVALID LABEL DETAILS
# -------------------------------------

for split in SPLITS:

    if invalid_labels[split]:

        print(f"\n========== {split.upper()} INVALID LABELS ==========\n")

        for item in invalid_labels[split]:
            print(item)

# -------------------------------------
# MISSING IMAGE DETAILS
# -------------------------------------

for split in SPLITS:

    if missing_images[split]:

        print(f"\n========== {split.upper()} MISSING IMAGES ==========\n")

        for item in missing_images[split]:
            print(item)

print("\n========== DATASET CHECK COMPLETED ==========")

========== CHECKING TRAIN ==========

========== CHECKING VAL ==========

========== CHECKING TEST ==========


========== FULL DATASET REPORT ==========

Total Images: 893
Total Annotations: 1748

========== SPLIT DISTRIBUTION ==========

TRAIN
Images       : 622
Annotations  : 1217

VAL
Images       : 179
Annotations  : 322

TEST
Images       : 92
Annotations  : 209

========== CLASS DISTRIBUTION ==========
Healthy (0)   : 897
Unhealthy (1) : 851

========== LABELING STATUS ==========

TRAIN
Need Labeling : 6

Missing Label Files:
  - healthy_0018.jpg
  - healthy_0038.jpg
  - healthy_0057.jpg
  - healthy_0059.jpg
  - healthy_0343.jpg
  - healthy_0157.jpg

VAL
Need Labeling : 1

Missing Label Files:
  - healthy_0108.jpg

TEST
Need Labeling : 0

========== OTHER ISSUES ==========

TRAIN
Missing Images : 1
Empty Labels   : 0
Invalid Labels : 0

VAL
Missing Images : 1
Empty Labels   : 1
Invalid Labels : 0

TEST
Missing Images : 1
Empty Labels   : 0
Invalid Labels : 0

========== VAL EMPTY LABELS ==========

healthy_0361.txt

========== TRAIN MISSING IMAGES ==========

classes.txt

========== VAL MISSING IMAGES ==========

classes.txt

========== TEST MISSING IMAGES ==========

classes.txt

========== DATASET CHECK COMPLETED ==========

In [9]:
print("\n========== MISSING IMAGE FILES ==========\n")

if len(missing_images) == 0:
    print("No missing images found!")

else:
    for i, item in enumerate(missing_images, start=1):
        print(f"{i}. {item}")

========== MISSING IMAGE FILES ==========

1. classes.txt
2. classes.txt
3. classes.txt

In [3]:
from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt

# LOAD MODEL
model = YOLO(
    "../runs/detect/models/trained/bitol_yolov8/weights/best.pt"
)

print("Model loaded successfully!")

# TEST EVALUATION
metrics = model.val(
    data="../detection_dataset/data.yaml",
    split="test"
)

print("Test evaluation completed!")

# OVERALL RESULTS
map50 = metrics.box.map50
map5095 = metrics.box.map
precision = metrics.box.mp
recall = metrics.box.mr

results_df = pd.DataFrame({
    "Metric": [
        "Precision",
        "Recall",
        "mAP50",
        "mAP50-95"
    ],
    "Score": [
        precision,
        recall,
        map50,
        map5095
    ]
})

display(results_df)

# CLASS-WISE RESULTS
class_names = ["healthy", "unhealthy"]

class_df = pd.DataFrame({
    "Class": class_names,
    "Precision": metrics.box.p,
    "Recall": metrics.box.r,
    "mAP50": metrics.box.ap50,
    "mAP50-95": metrics.box.ap
})

display(class_df)

# PLOT
plt.figure(figsize=(8,5))
plt.bar(results_df["Metric"], results_df["Score"])
plt.ylim(0,1)
plt.title("Overall Test Performance")
plt.show()

# PREDICTION
results = model.predict(
    source="../detection_dataset/images/test",
    save=True,
    conf=0.5
)

print("Prediction completed!")

Model loaded successfully!
Ultralytics 8.4.51  Python-3.14.5 torch-2.12.0+cpu CPU (11th Gen Intel Core i5-1135G7 @ 2.40GHz)
Model summary (fused): 73 layers, 3,006,038 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access  (ping: 0.00.0 ms, read: 1266.9442.7 MB/s, size: 400.1 KB)
val: Scanning W:\CODE\Bitol_Computer_Vision_System\detection_dataset\labels\test.cache... 51 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 51/51 8.6Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 2.8s/it 11.2s5.1ss
                   all         51        110      0.746      0.746      0.746      0.408
               healthy         14         43      0.553      0.836      0.646      0.304
             unhealthy         37         67      0.939      0.657      0.847      0.512
Speed: 3.7ms preprocess, 193.4ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to W:\CODE\Bitol_Computer_Vision_System\notebooks\runs\detect\val
Test evaluation completed!

      Metric     Score
0  Precision  0.745939
1     Recall  0.746139
2      mAP50  0.746294
3   mAP50-95  0.408367

       Class  Precision    Recall     mAP50  mAP50-95
0    healthy   0.553352  0.835562  0.645898  0.304282
1  unhealthy   0.938526  0.656716  0.846691  0.512452

image 1/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0125.jpg: 1024x1024 1 healthy, 212.8ms
image 2/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0126.jpg: 1024x1024 3 healthys, 190.4ms
image 3/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0127.jpg: 1024x1024 2 healthys, 183.1ms
image 4/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0128.jpg: 1024x1024 2 healthys, 182.8ms
image 5/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0129.jpg: 1024x1024 1 healthy, 183.5ms
image 6/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0130.jpg: 1024x1024 1 healthy, 187.5ms
image 7/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0131.jpg: 1024x1024 4 healthys, 181.3ms
image 8/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0132.jpg: 1024x1024 1 healthy, 197.0ms
image 9/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0133.jpg: 1024x1024 1 healthy, 197.3ms
image 10/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0134.jpg: 1024x1024 2 healthys, 196.8ms
image 11/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0135.jpg: 1024x1024 2 healthys, 190.0ms
image 12/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0136.jpg: 1024x1024 (no detections), 182.9ms
image 13/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0137.jpg: 1024x1024 2 healthys, 180.2ms
image 14/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0138.jpg: 1024x1024 2 healthys, 235.7ms
image 15/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0324.jpg: 1024x1024 1 unhealthy, 235.8ms
image 16/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0325.jpg: 1024x1024 1 unhealthy, 203.0ms
image 17/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0326.jpg: 1024x1024 1 unhealthy, 242.8ms
image 18/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0327.jpg: 1024x1024 1 unhealthy, 180.6ms
image 19/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0328.jpg: 1024x1024 1 unhealthy, 189.2ms
image 20/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0329.jpg: 1024x1024 1 unhealthy, 188.4ms
image 21/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0330.jpg: 1024x1024 1 unhealthy, 205.4ms
image 22/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0331.jpg: 1024x1024 1 unhealthy, 186.6ms
image 23/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0332.jpg: 1024x1024 1 unhealthy, 187.7ms
image 24/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0333.jpg: 1024x1024 1 unhealthy, 191.6ms
image 25/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0334.jpg: 1024x1024 1 unhealthy, 187.1ms
image 26/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0335.jpg: 1024x1024 2 unhealthys, 184.4ms
image 27/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0336.jpg: 1024x1024 1 unhealthy, 188.6ms
image 28/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0337.jpg: 1024x1024 1 unhealthy, 189.5ms
image 29/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0338.jpg: 1024x1024 1 unhealthy, 205.1ms
image 30/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0339.jpg: 1024x1024 1 unhealthy, 183.4ms
image 31/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0340.jpg: 1024x1024 1 unhealthy, 184.6ms
image 32/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0341.jpg: 1024x1024 1 unhealthy, 191.8ms
image 33/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0342.jpg: 1024x1024 1 unhealthy, 193.9ms
image 34/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0343.jpg: 1024x1024 1 unhealthy, 193.2ms
image 35/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0344.jpg: 1024x1024 2 unhealthys, 251.4ms
image 36/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0345.jpg: 1024x1024 1 unhealthy, 206.8ms
image 37/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0346.jpg: 1024x1024 1 unhealthy, 228.3ms
image 38/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0347.jpg: 1024x1024 1 unhealthy, 202.2ms
image 39/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0348.jpg: 1024x1024 1 unhealthy, 200.4ms
image 40/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0349.jpg: 1024x1024 2 unhealthys, 185.2ms
image 41/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0350.jpg: 1024x1024 1 healthy, 2 unhealthys, 211.8ms
image 42/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0351.jpg: 1024x1024 2 healthys, 177.2ms
image 43/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0352.jpg: 1024x1024 1 healthy, 177.8ms
image 44/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0353.jpg: 1024x1024 4 healthys, 188.3ms
image 45/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0354.jpg: 1024x1024 1 unhealthy, 180.2ms
image 46/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0355.jpg: 1024x1024 3 healthys, 184.5ms
image 47/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0356.jpg: 1024x1024 (no detections), 183.2ms
image 48/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0357.jpg: 1024x1024 3 healthys, 180.4ms
image 49/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0358.jpg: 1024x1024 (no detections), 184.0ms
image 50/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0359.jpg: 1024x1024 4 unhealthys, 185.0ms
image 51/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0360.jpg: 1024x1024 3 unhealthys, 187.5ms
Speed: 10.6ms preprocess, 194.7ms inference, 1.3ms postprocess per image at shape (1, 3, 1024, 1024)
Results saved to W:\CODE\Bitol_Computer_Vision_System\notebooks\runs\detect\predict
Prediction completed!

In [1]:
from ultralytics import YOLO
import pandas as pd
import matplotlib.pyplot as plt

# ==========================================
# LOAD MODEL
# ==========================================

model = YOLO(
    "../runs/detect/models/trained/bitol_yolov8/weights/best.pt"
)

print("Model loaded successfully!")

# ==========================================
# TEST EVALUATION
# ==========================================

metrics = model.val(
    data="../detection_dataset/data.yaml",
    split="test"
)

print("Test evaluation completed!")

# ==========================================
# OVERALL METRICS
# ==========================================

map50 = metrics.box.map50
map5095 = metrics.box.map
precision = metrics.box.mp
recall = metrics.box.mr

# F1 Score
f1_score = (2 * precision * recall) / (precision + recall)

results_df = pd.DataFrame({
    "Metric": [
        "Precision",
        "Recall",
        "F1-Score",
        "mAP50",
        "mAP50-95"
    ],
    "Score": [
        precision,
        recall,
        f1_score,
        map50,
        map5095
    ]
})

print("\n========== OVERALL TEST RESULTS ==========\n")

display(results_df)

# ==========================================
# CLASS-WISE RESULTS
# ==========================================

class_names = ["healthy", "unhealthy"]

class_precision = metrics.box.p
class_recall = metrics.box.r

# CLASS-WISE F1
class_f1 = (
    2 * class_precision * class_recall
) / (
    class_precision + class_recall
)

class_df = pd.DataFrame({
    "Class": class_names,
    "Precision": class_precision,
    "Recall": class_recall,
    "F1-Score": class_f1,
    "mAP50": metrics.box.ap50,
    "mAP50-95": metrics.box.ap
})

print("\n========== CLASS-WISE RESULTS ==========\n")

display(class_df)

# ==========================================
# OVERALL METRIC PLOT
# ==========================================

plt.figure(figsize=(10,5))

plt.bar(
    results_df["Metric"],
    results_df["Score"]
)

plt.ylim(0,1)

plt.title("Overall Test Performance")

plt.ylabel("Score")

plt.show()

# ==========================================
# CLASS-WISE MAP50 PLOT
# ==========================================

plt.figure(figsize=(6,5))

plt.bar(
    class_df["Class"],
    class_df["mAP50"]
)

plt.ylim(0,1)

plt.title("Healthy vs Unhealthy mAP50")

plt.ylabel("mAP50")

plt.show()

# ==========================================
# CLASS-WISE F1 PLOT
# ==========================================

plt.figure(figsize=(6,5))

plt.bar(
    class_df["Class"],
    class_df["F1-Score"]
)

plt.ylim(0,1)

plt.title("Healthy vs Unhealthy F1-Score")

plt.ylabel("F1-Score")

plt.show()

# ==========================================
# PREDICTION
# ==========================================

results = model.predict(
    source="../detection_dataset/images/test",
    save=True,
    conf=0.5
)

print("\nPrediction completed!")

print("\nPrediction images saved inside:")

print("runs/detect/predict")

Model loaded successfully!
Ultralytics 8.4.51  Python-3.14.5 torch-2.12.0+cpu CPU (11th Gen Intel Core i5-1135G7 @ 2.40GHz)
Model summary (fused): 73 layers, 3,006,038 parameters, 0 gradients, 8.1 GFLOPs
val: Fast image access  (ping: 0.20.1 ms, read: 40.913.5 MB/s, size: 297.3 KB)
val: Scanning W:\CODE\Bitol_Computer_Vision_System\detection_dataset\labels\test.cache... 51 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 51/51 9.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 2.7s/it 10.9s5.0ss
                   all         51        110      0.746      0.746      0.746      0.408
               healthy         14         43      0.553      0.836      0.646      0.304
             unhealthy         37         67      0.939      0.657      0.847      0.512
Speed: 4.0ms preprocess, 173.8ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to W:\CODE\Bitol_Computer_Vision_System\notebooks\runs\detect\val-2
Test evaluation completed!

========== OVERALL TEST RESULTS ==========

      Metric     Score
0  Precision  0.745939
1     Recall  0.746139
2   F1-Score  0.746039
3      mAP50  0.746294
4   mAP50-95  0.408367

========== CLASS-WISE RESULTS ==========

       Class  Precision    Recall  F1-Score     mAP50  mAP50-95
0    healthy   0.553352  0.835562  0.665786  0.645898  0.304282
1  unhealthy   0.938526  0.656716  0.772730  0.846691  0.512452

image 1/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0125.jpg: 1024x1024 1 healthy, 224.3ms
image 2/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0126.jpg: 1024x1024 3 healthys, 185.9ms
image 3/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0127.jpg: 1024x1024 2 healthys, 181.6ms
image 4/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0128.jpg: 1024x1024 2 healthys, 243.6ms
image 5/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0129.jpg: 1024x1024 1 healthy, 190.9ms
image 6/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0130.jpg: 1024x1024 1 healthy, 217.8ms
image 7/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0131.jpg: 1024x1024 4 healthys, 167.7ms
image 8/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0132.jpg: 1024x1024 1 healthy, 167.7ms
image 9/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0133.jpg: 1024x1024 1 healthy, 185.8ms
image 10/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0134.jpg: 1024x1024 2 healthys, 339.3ms
image 11/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0135.jpg: 1024x1024 2 healthys, 235.2ms
image 12/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0136.jpg: 1024x1024 (no detections), 233.5ms
image 13/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0137.jpg: 1024x1024 2 healthys, 185.7ms
image 14/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\healthy_0138.jpg: 1024x1024 2 healthys, 193.7ms
image 15/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0324.jpg: 1024x1024 1 unhealthy, 215.6ms
image 16/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0325.jpg: 1024x1024 1 unhealthy, 215.0ms
image 17/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0326.jpg: 1024x1024 1 unhealthy, 315.6ms
image 18/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0327.jpg: 1024x1024 1 unhealthy, 211.5ms
image 19/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0328.jpg: 1024x1024 1 unhealthy, 194.1ms
image 20/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0329.jpg: 1024x1024 1 unhealthy, 197.9ms
image 21/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0330.jpg: 1024x1024 1 unhealthy, 192.1ms
image 22/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0331.jpg: 1024x1024 1 unhealthy, 183.0ms
image 23/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0332.jpg: 1024x1024 1 unhealthy, 190.5ms
image 24/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0333.jpg: 1024x1024 1 unhealthy, 180.7ms
image 25/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0334.jpg: 1024x1024 1 unhealthy, 219.1ms
image 26/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0335.jpg: 1024x1024 2 unhealthys, 216.0ms
image 27/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0336.jpg: 1024x1024 1 unhealthy, 187.0ms
image 28/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0337.jpg: 1024x1024 1 unhealthy, 188.7ms
image 29/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0338.jpg: 1024x1024 1 unhealthy, 180.1ms
image 30/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0339.jpg: 1024x1024 1 unhealthy, 201.0ms
image 31/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0340.jpg: 1024x1024 1 unhealthy, 169.7ms
image 32/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0341.jpg: 1024x1024 1 unhealthy, 187.2ms
image 33/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0342.jpg: 1024x1024 1 unhealthy, 240.3ms
image 34/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0343.jpg: 1024x1024 1 unhealthy, 217.9ms
image 35/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0344.jpg: 1024x1024 2 unhealthys, 243.7ms
image 36/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0345.jpg: 1024x1024 1 unhealthy, 172.3ms
image 37/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0346.jpg: 1024x1024 1 unhealthy, 180.7ms
image 38/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0347.jpg: 1024x1024 1 unhealthy, 166.7ms
image 39/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0348.jpg: 1024x1024 1 unhealthy, 172.4ms
image 40/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0349.jpg: 1024x1024 2 unhealthys, 167.8ms
image 41/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0350.jpg: 1024x1024 1 healthy, 2 unhealthys, 165.8ms
image 42/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0351.jpg: 1024x1024 2 healthys, 200.6ms
image 43/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0352.jpg: 1024x1024 1 healthy, 179.6ms
image 44/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0353.jpg: 1024x1024 4 healthys, 189.3ms
image 45/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0354.jpg: 1024x1024 1 unhealthy, 205.3ms
image 46/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0355.jpg: 1024x1024 3 healthys, 188.0ms
image 47/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0356.jpg: 1024x1024 (no detections), 192.9ms
image 48/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0357.jpg: 1024x1024 3 healthys, 200.3ms
image 49/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0358.jpg: 1024x1024 (no detections), 266.9ms
image 50/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0359.jpg: 1024x1024 4 unhealthys, 259.9ms
image 51/51 w:\CODE\Bitol_Computer_Vision_System\notebooks\..\detection_dataset\images\test\unhealthy_0360.jpg: 1024x1024 3 unhealthys, 213.0ms
Speed: 10.8ms preprocess, 204.3ms inference, 1.4ms postprocess per image at shape (1, 3, 1024, 1024)
Results saved to W:\CODE\Bitol_Computer_Vision_System\notebooks\runs\detect\predict-2

Prediction completed!

Prediction images saved inside:
runs/detect/predict